author:           "Theirry Nicole Panggabean"
navbarlinks:
- navbar:         "Home"
  link:           "/"
- navbar:         "Links"
  link:           "/LINKS/"
- navbar:         "GitHub"
  link:           "https://github.com/nicolepanggabean/os222"
- navbar:         "Log"
  link:           "/TXT/my.log.txt"

